### ISSUE TITLE
Feature Request: Need a function to get the current status...

### ISSUE THREAD

**Issue by jahagirdar** [smemsh/python-timew#1]
For an application I am writing, i need the parsed result of `timew` command.
i.e.
Is the tracker on?
If on, what is the task, start time and its duration...
If the tracker is not on, then it can return None...

**Comment by smemsh** [comment]
These seem like application level inquiries.  You could use the library to export @1 and get everything you asked for from that datum, right? if there's no `end`, the "tracker is on."  I assume by "what is the task" you mean any tags (which don't have to exist btw), these are also available in the returned object's `tags`.
